# requiring the environment of NodeJS 10
image: ubuntu:16.04

before_script:
   ##
   ## Install ssh-agent if not already installed, it is required by Docker.
   ## (change apt-get to yum if you use an RPM-based image)
   ##
   - apt-get update -y
   - apt-get install apt-transport-https wget lsb-release -y
   - rm /etc/apt/sources.list
   - wget https://isrc.iscas.ac.cn/mirror/help/mirror/xlab_ubuntu16.04.list -O /etc/apt/sources.list.d/xlab_ubuntu16.04.list
   - wget -qO - https://isrc.iscas.ac.cn/mirror/ros/ros.gpg | apt-key add -
   - sh -c 'echo "deb https://isrc.iscas.ac.cn/mirror/ros/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
   - wget -qO - https://isrc.iscas.ac.cn/mirror/xbot/xbot.gpg | apt-key add -
   - wget https://isrc.iscas.ac.cn/mirror/help/mirror/xbot-xenial-test-amd64.list -O /etc/apt/sources.list.d/xbot-xenial-test-amd64.list
   - apt-get update -y
   - apt-get install -y openssh-client dpkg-dev devscripts build-essential equivs fakeroot

   ##
   ## Run ssh-agent (inside the build environment)
   ##
   - eval $(ssh-agent -s)

   ##
   ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
   ## We're using tr to fix line endings which makes ed25519 keys work
   ## without extra base64 encoding.
   ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
   ##
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   ##
   ## Create the SSH directory and give it the right permissions
   ##
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   ##
   ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
   ## following two lines.
   ##
   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  tags:
    - xeniel
  script:
    - cd xbot_bringup
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-bringup-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - scp -P 1022 ../ros-kinetic-xbot-bringup_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-bringup
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-bringup_*.deb
    - cd ../
    - cd xbot_description
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-description-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - scp -P 1022 ../ros-kinetic-xbot-description_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-description
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-description_*.deb
    - cd ../
    - cd xbot_driver
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-driver-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - scp -P 1022 ../ros-kinetic-xbot-driver_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-driver
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-driver_*.deb
    - cd ../
    - cd xbot_msgs
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-msgs-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - scp -P 1022 ../ros-kinetic-xbot-msgs_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-msgs
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-msgs_*.deb
    - cd ../
    - cd xbot_tools
    - mk-build-deps
    - apt-get update -y
    - apt install -y ./ros-kinetic-xbot-tools-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - scp -P 1022 ../ros-kinetic-xbot-tools_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-tools
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-tools_*.deb
    - cd ../
    - cd xbot_safety_controller
    - mk-build-deps
    - apt-get update -y
    - apt install -y ./ros-kinetic-xbot-safety-controller-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - scp -P 1022 ../ros-kinetic-xbot-safety-controller_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-safety-controller
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-safety-controller_*.deb
    - cd ../
    - cd xbot_node
    - mk-build-deps
    - apt-get update -y
    - apt install -y ./ros-kinetic-xbot-node-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - scp -P 1022 ../ros-kinetic-xbot-node_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-node
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-node_*.deb
  only:
    - imudown