image: ubuntu:16.04

before_script:
  - rm /etc/apt/sources.list
  - echo deb http://isrc.iscas.ac.cn/mirror/ubuntu/ xenial main restricted universe multiverse > /etc/apt/sources.list
  - echo deb http://isrc.iscas.ac.cn/mirror/ubuntu/ xenial-updates main restricted universe multiverse >> /etc/apt/sources.list
  - echo deb http://isrc.iscas.ac.cn/mirror/ubuntu/ xenial-security main restricted universe multiverse >> /etc/apt/sources.list
  - apt-get update -y

build:
  stage: build
  tags:
    - xenial
    - deb
  script:
    - export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
    - apt-get install apt-transport-https wget lsb-release gnupg -y
    - wget -qO - https://isrc.iscas.ac.cn/mirror/ros/ros.gpg | apt-key add -
    - sh -c 'echo "deb https://isrc.iscas.ac.cn/mirror/ros/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget -qO - https://isrc.iscas.ac.cn/mirror/xbot/xbot.gpg | apt-key add -
    - wget https://isrc.iscas.ac.cn/mirror/help/mirror/xbot-xenial-test-amd64.list -O /etc/apt/sources.list.d/xbot-xenial-test-amd64.list
    - apt-get update -y
    - apt-get install -y dpkg-dev devscripts build-essential equivs fakeroot
    - mkdir public
    - cd xbot_bringup
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-bringup-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - mv ../ros-kinetic-xbot-bringup_* ../public/
    - cd ../
    - cd xbot_description
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-description-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - mv ../ros-kinetic-xbot-description_* ../public/
    - cd ../
    - cd xbot_driver
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-driver-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - mv ../ros-kinetic-xbot-driver_* ../public/
    - cd ../
    - cd xbot_msgs
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-msgs-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - mv ../ros-kinetic-xbot-msgs_* ../public/
    - cd ../
    - cd xbot_tools
    - mk-build-deps
    - apt-get update -y
    - apt install -y ./ros-kinetic-xbot-tools-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - mv ../ros-kinetic-xbot-tools_* ../public/
    - cd ../
    - cd xbot_safety_controller
    - mk-build-deps
    - apt-get update -y
    - apt install -y ./ros-kinetic-xbot-safety-controller-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - mv ../ros-kinetic-xbot-safety-controller_* ../public/
    - cd ../
    - cd xbot_node
    - mk-build-deps
    - apt-get update -y
    - apt install -y ./ros-kinetic-xbot-node-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - mv ../ros-kinetic-xbot-node_* ../public/
    - cd ../
  artifacts:
    paths:
      - public
    expire_in: 1 week

deploy:
  stage: deploy
  dependencies:
    - build
  tags:
    - xenial
    - deb
  script:
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp -P 1022 ./public/ros-kinetic-xbot-bringup_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-bringup
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-bringup_*.deb
    - scp -P 1022 ./public/ros-kinetic-xbot-description_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-description
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-description_*.deb
    - scp -P 1022 ./public/ros-kinetic-xbot-driver_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-driver
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-driver_*.deb
    - scp -P 1022 ./public/ros-kinetic-xbot-msgs_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-msgs
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-msgs_*.deb
    - scp -P 1022 ./public/ros-kinetic-xbot-tools_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-tools
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-tools_*.deb
    - scp -P 1022 ./public/ros-kinetic-xbot-safety-controller_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-safety-controller
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-safety-controller_*.deb
    - scp -P 1022 ./public/ros-kinetic-xbot-node_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-node
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-node_*.deb
  only:
    refs:
      - tags
    changes:
      - "debian/changelog"
