image: ubuntu:16.04

before_script:
  - rm /etc/apt/sources.list
  - echo deb http://isrc.iscas.ac.cn/mirror/ubuntu/ xenial main restricted universe multiverse > /etc/apt/sources.list
  - echo deb http://isrc.iscas.ac.cn/mirror/ubuntu/ xenial-updates main restricted universe multiverse >> /etc/apt/sources.list
  - echo deb http://isrc.iscas.ac.cn/mirror/ubuntu/ xenial-security main restricted universe multiverse >> /etc/apt/sources.list
  - apt-get update -y

build:
  stage: build
  tags:
    - xenial
    - deb
  script:
    - apt-get install apt-transport-https wget lsb-release -y
    - wget -qO - https://isrc.iscas.ac.cn/mirror/ros/ros.gpg | apt-key add -
    - sh -c 'echo "deb http://isrc.iscas.ac.cn/mirror/ros/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget -qO - https://isrc.iscas.ac.cn/mirror/xbot/xbot.gpg | apt-key add -
    - wget https://isrc.iscas.ac.cn/mirror/help/mirror/xbot-xenial-test-amd64.list -O /etc/apt/sources.list.d/xbot-xenial-test-amd64.list
    - apt-get update -y
    - apt-get install -y dpkg-dev devscripts build-essential equivs fakeroot
    - mkdir public
    - mk-build-deps
    - apt install -y ./ros-kinetic-xbot-talker-build-deps*.deb
    - dpkg-buildpackage -rfakeroot -uc -us
    - mv ../ros-kinetic-xbot-talker_* ./public/
  artifacts:
    paths:
    - public
    expire_in: 1 week

deploy:
  stage: deploy
  dependencies:
    - build
  tags:
    - xenial
    - deb
  script:
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp -P 1022 ./public/ros-kinetic-xbot-talker_*.deb reprepro@192.168.8.12:/data/tmpdeb/
    - ssh -p 1022 reprepro@192.168.8.12 reprepro remove xenial_test ros-kinetic-xbot-talker
    - ssh -p 1022 reprepro@192.168.8.12 reprepro --delete includedeb xenial_test /data/tmpdeb/ros-kinetic-xbot-talker_*.deb
  only:
    refs:
      - tags
    changes:
      - "debian/changelog"