<?xml version="1.0"?>
<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 415 camera, in its
aluminum peripherial evaluation case.
-->
<robot name="sensor_d415" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Includes -->
  <xacro:include filename="$(find xbot_description)/urdf/_materials.urdf.xacro">
  </xacro:include>
  <xacro:include filename="$(find xbot_description)/urdf/_usb_plug.urdf.xacro">
  </xacro:include>
  <xacro:macro name="sensor_d415" params="parent *origin  name:=camera">
    <xacro:property name="M_PI" value="3.1415926535897931">
    </xacro:property>
    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d415_cam_depth_to_infra1_offset" value="0.0">
    </xacro:property>
    <xacro:property name="d415_cam_depth_to_infra2_offset" value="-0.055">
    </xacro:property>
    <xacro:property name="d415_cam_depth_to_color_offset" value="0.015">
    </xacro:property>
    <!-- The following values model the aluminum peripherial case for the
    d415 camera, with the camera joint represented by the actual
    peripherial camera tripod mount -->
    <xacro:property name="d415_cam_width" value="0.099">
    </xacro:property>
    <xacro:property name="d415_cam_height" value="0.023">
    </xacro:property>
    <xacro:property name="d415_cam_depth" value="0.02005">
    </xacro:property>
    <xacro:property name="d415_cam_mount_from_center_offset" value="0.00987">
    </xacro:property>
    <!-- The following offset is relative the the physical d415 camera peripherial
    camera tripod mount -->
    <xacro:property name="d415_cam_depth_px" value="${d415_cam_mount_from_center_offset}">
    </xacro:property>
    <xacro:property name="d415_cam_depth_py" value="0.020">
    </xacro:property>
    <xacro:property name="d415_cam_depth_pz" value="${d415_cam_height/2}">
    </xacro:property>
    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin">
      </xacro:insert_block>
      <parent link="${parent}">
      </parent>
      <child link="${name}_bottom_screw_frame">
      </child>
    </joint>
    <link name="${name}_bottom_screw_frame"/>
    <joint name="${name}_link_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 ${d415_cam_depth_py} ${d415_cam_depth_pz}">
      </origin>
      <parent link="${name}_bottom_screw_frame">
      </parent>
      <child link="${name}_link">
      </child>
    </joint>
    <link name="${name}_link">
      <visual>
        <origin rpy="${M_PI/2} 0 ${M_PI/2}" xyz="${d415_cam_mount_from_center_offset} ${-d415_cam_depth_py} 0">
        </origin>
        <geometry>
          <!-- <box size="${d415_cam_width} ${d415_cam_height} ${d415_cam_depth}"/> -->
          <mesh filename="package://xbot_description/models/camera/d415.stl">
          </mesh>
        </geometry>
        <material name="aluminum">
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 ${-d415_cam_depth_py} 0">
        </origin>
        <geometry>
          <box size="${d415_cam_depth} ${d415_cam_width} ${d415_cam_height}">
          </box>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564">
        </mass>
        <origin xyz="0 0 0">
        </origin>
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257">
        </inertia>
      </inertial>
    </link>
    <!-- camera depth joints and links -->
    <joint name="${name}_depth_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0">
      </origin>
      <parent link="${name}_link">
      </parent>
      <child link="${name}_depth_frame">
      </child>
    </joint>
    <link name="${name}_depth_frame"/>
    <joint name="${name}_depth_optical_joint" type="fixed">
      <origin rpy="${-M_PI/2} 0 ${-M_PI/2}" xyz="0 0 0">
      </origin>
      <parent link="${name}_depth_frame">
      </parent>
      <child link="${name}_depth_optical_frame">
      </child>
    </joint>
    <link name="${name}_depth_optical_frame"/>
    <!-- camera left IR joints and links -->
    <joint name="${name}_infra1_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 ${d415_cam_depth_to_infra1_offset} 0">
      </origin>
      <parent link="${name}_link">
      </parent>
      <child link="${name}_infra1_frame">
      </child>
    </joint>
    <link name="${name}_infra1_frame"/>
    <joint name="${name}_infra1_optical_joint" type="fixed">
      <origin rpy="${-M_PI/2} 0 ${-M_PI/2}" xyz="0 0 0">
      </origin>
      <parent link="${name}_infra1_frame">
      </parent>
      <child link="${name}_infra1_optical_frame">
      </child>
    </joint>
    <link name="${name}_infra1_optical_frame"/>
    <!-- camera right IR joints and links -->
    <joint name="${name}_infra2_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 ${d415_cam_depth_to_infra2_offset} 0">
      </origin>
      <parent link="${name}_link">
      </parent>
      <child link="${name}_infra2_frame">
      </child>
    </joint>
    <link name="${name}_infra2_frame"/>
    <joint name="${name}_infra2_optical_joint" type="fixed">
      <origin rpy="${-M_PI/2} 0 ${-M_PI/2}" xyz="0 0 0">
      </origin>
      <parent link="${name}_infra2_frame">
      </parent>
      <child link="${name}_infra2_optical_frame">
      </child>
    </joint>
    <link name="${name}_infra2_optical_frame"/>
    <!-- camera color joints and links -->
    <joint name="${name}_color_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 ${d415_cam_depth_to_color_offset} 0">
      </origin>
      <parent link="${name}_link">
      </parent>
      <child link="${name}_color_frame">
      </child>
    </joint>
    <link name="${name}_color_frame"/>
    <joint name="${name}_color_optical_joint" type="fixed">
      <origin rpy="${-M_PI/2} 0 ${-M_PI/2}" xyz="0 0 0">
      </origin>
      <parent link="${name}_color_frame">
      </parent>
      <child link="${name}_color_optical_frame">
      </child>
    </joint>
    <link name="${name}_color_optical_frame"/>
    <xacro:usb_plug name="${name}_usb_plug" parent="${name}_link">
      <origin rpy="0 0 0" xyz="${d415_cam_mount_from_center_offset - 0.01587} ${-d415_cam_depth_py - 0.0358} 0">
      </origin>
    </xacro:usb_plug>
  </xacro:macro>
</robot>
